name: Deploy Laravel Project on push

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Optimize Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-
      - name: Install PHP dependencies
        run: composer install --ignore-platform-reqs --no-interaction

      # Parallelize initial setup steps
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link

      # Optimize directory permissions and deploy via FTP using appleboy/ftp-action
      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Deploy via FTP
        uses: appleboy/ftp-action@v0.2.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./ # This specifies the directory to upload
          remoteDir: /topbusiness/public_html/spa/public/  # Update this path to your desired directory
          parallel: 10 # Adjust the number of parallel connections for faster uploads
