name: Deploy Laravel Project on push

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Optimize Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-

      # Install PHP dependencies
      - name: Install PHP dependencies
        run: composer install --ignore-platform-reqs --no-interaction

      # Generate key and storage link in parallel
      - name: Generate key and storage link
        run: |
          php artisan key:generate &
          php artisan storage:link
        # ...

      # Set directory permissions
      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      # Deploy via FTP using sebastianpopp/ftp-action@releases/v2
      - name: Deploy via FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          server: ${{ secrets.INPUT_SERVER }}
          username: ${{ secrets.INPUT_USERNAME }}
          password: ${{ secrets.INPUT_PASSWORD }}
          local-dir: ./ # This specifies the directory to upload
          server-dir: /topbusiness/public_html/spa/public/  # Update this path to your desired directory
